"""Pure domain rules; framework and infrastructure imports are forbidden."""

from .characters import Character, CharacterProfile, CharacterState
from .clock import ClockInterval, ClockPolicy, InWorldClock
from .content import (
    ConsentRecord,
    ConsentRequirements,
    ConsentState,
    ContentDecision,
    ContentPolicy,
    ContentPolicyOverride,
    PolicyDecision,
    Rating,
    SceneSpec,
    TopicBoundary,
    ViolenceCeiling,
    evaluate_scene,
)
from .engine import AppliedPatch, DomainEngine, DomainRuntime, apply_patch, replay_patches, revert_patch
from .errors import DomainError, DomainValidationError, GuardRejected
from .events import Belief, Event, Evidence, Observation, ScheduledEvent
from .guard import DomainGuard, GuardResult
from .knowledge import (
    CanonFact,
    CanonFactStatus,
    ClaimLink,
    ClaimLinkKind,
    KnowledgeClaim,
    PredicateDefinition,
    PredicateRegistry,
)
from .language import StoryLanguage
from .narrative import HookStatus, NarrativeHook, NarrativeThread, ThreadStatus
from .patch import (
    AddClaimLink,
    AddEvent,
    AddEvidence,
    AddHook,
    AddKnowledgeClaim,
    AddObservation,
    AddThread,
    AdvanceClock,
    ApplyRelationshipDelta,
    AssertCanonFact,
    ConsentTransition,
    MaterializeScheduledEvent,
    RelationshipDelta,
    ScheduleEvent,
    SetCharacterCondition,
    SetCharacterLocation,
    StateOperation,
    StatePatch,
    TransitionHook,
    TransitionThread,
    UpdateBelief,
    UpdatePsychology,
)
from .psychology import PsychologicalState
from .relationships import (
    DEFAULT_RELATIONSHIP_POLICIES,
    RELATIONSHIP_BOUNDS,
    RelationshipChange,
    RelationshipDimension,
    RelationshipPolicy,
    RelationshipVector,
    derive_familiarity,
)
from .state import GameState
from .values import MINUTES_PER_DAY, MINUTES_PER_YEAR, Provenance, TimeRange, clamp

__all__ = [
    "AddEvent",
    "AddEvidence",
    "AddHook",
    "AddClaimLink",
    "AddKnowledgeClaim",
    "AddObservation",
    "AddThread",
    "AdvanceClock",
    "AppliedPatch",
    "ApplyRelationshipDelta",
    "AssertCanonFact",
    "Belief",
    "CanonFact",
    "CanonFactStatus",
    "Character",
    "CharacterProfile",
    "CharacterState",
    "ClaimLink",
    "ClaimLinkKind",
    "ClockInterval",
    "ClockPolicy",
    "ConsentRecord",
    "ConsentRequirements",
    "ConsentState",
    "ConsentTransition",
    "ContentDecision",
    "ContentPolicy",
    "ContentPolicyOverride",
    "DEFAULT_RELATIONSHIP_POLICIES",
    "DomainEngine",
    "DomainError",
    "DomainGuard",
    "DomainRuntime",
    "DomainValidationError",
    "Event",
    "Evidence",
    "GameState",
    "GuardRejected",
    "GuardResult",
    "HookStatus",
    "InWorldClock",
    "KnowledgeClaim",
    "MaterializeScheduledEvent",
    "ScheduleEvent",
    "StoryLanguage",
    "MINUTES_PER_DAY",
    "MINUTES_PER_YEAR",
    "NarrativeHook",
    "NarrativeThread",
    "Observation",
    "ScheduledEvent",
    "PolicyDecision",
    "PredicateDefinition",
    "PredicateRegistry",
    "PsychologicalState",
    "Provenance",
    "Rating",
    "RelationshipChange",
    "RelationshipDelta",
    "RelationshipDimension",
    "RelationshipPolicy",
    "RelationshipVector",
    "RELATIONSHIP_BOUNDS",
    "replay_patches",
    "revert_patch",
    "SceneSpec",
    "SetCharacterCondition",
    "SetCharacterLocation",
    "StateOperation",
    "StatePatch",
    "ThreadStatus",
    "TimeRange",
    "TopicBoundary",
    "TransitionHook",
    "TransitionThread",
    "UpdateBelief",
    "UpdatePsychology",
    "ViolenceCeiling",
    "apply_patch",
    "clamp",
    "derive_familiarity",
    "evaluate_scene",
]
