"""Application-facing records and contracts."""

from .ai import (
    AIOutput,
    AIPromptRole,
    ConsistencyReport,
    CritiqueResult,
    KnowledgeClaimProposal,
    KnowledgeRequirement,
    LLMRunTrace,
    NarrativeDraft,
    ParseStatus,
    SceneSpec,
    SimulationResult,
    StatePatchProposal,
    TurnPlan,
    WorldSeed,
)
from .persistence import CharacterRecord, PlaythroughRecord, WorldRecord
from .providers import ProviderRequest, ProviderRoutingConfig, ProviderTarget
from .retrieval import (
    PUBLIC_OWNER,
    ClaimExtractionResult,
    ContextEntry,
    EmbeddingMetadata,
    EmbeddingRecord,
    InitialContextManifest,
    InitialContextRequest,
    MemoryCandidate,
    MemoryKind,
    RetrievalHit,
    RetrievalPhase,
    RetrievalQuery,
    RetrievalScope,
    RetrievalTrace,
    RetrievalTraceHit,
    ScoreBreakdown,
    canonical_value,
    content_hash,
)

__all__ = [
    "AIOutput",
    "AIPromptRole",
    "ConsistencyReport",
    "ClaimExtractionResult",
    "CharacterRecord",
    "ContextEntry",
    "CritiqueResult",
    "EmbeddingMetadata",
    "EmbeddingRecord",
    "InitialContextManifest",
    "InitialContextRequest",
    "KnowledgeClaimProposal",
    "KnowledgeRequirement",
    "LLMRunTrace",
    "MemoryCandidate",
    "MemoryKind",
    "NarrativeDraft",
    "ParseStatus",
    "PlaythroughRecord",
    "ProviderRequest",
    "ProviderRoutingConfig",
    "ProviderTarget",
    "PUBLIC_OWNER",
    "RetrievalHit",
    "RetrievalPhase",
    "RetrievalQuery",
    "RetrievalScope",
    "RetrievalTrace",
    "RetrievalTraceHit",
    "ScoreBreakdown",
    "SceneSpec",
    "SimulationResult",
    "StatePatchProposal",
    "TurnPlan",
    "WorldRecord",
    "WorldSeed",
    "canonical_value",
    "content_hash",
]
